### ISSUE TITLE
Dockerfile to run CDT.cloud blueprint

### ISSUE THREAD

**Issue by planger** [eclipse-cdt-cloud/cdt-cloud-blueprint#10]
CDT.cloud has several dependencies regarding the system it runs in, such as clangd, potentially a build tool like CMake, etc.
Therefore, it might be helpful to provide a dockerfile that defines those requirements and harmonizes the environment that we use for testing. Also this could be the starting point to deploy CDT.cloud in a kubernetes based cloud infrastructure.

See also the corresponding [discussion thread](https://github.com/eclipse-cdt-cloud/cdt-cloud/discussions/3).

**Comment by sdirix** [comment]
Implemented with #14
