### ISSUE TITLE
Build sign and deploy Blueprint artifacts automatically from master branch

### ISSUE THREAD

**Issue by sdirix** [eclipse-cdt-cloud/cdt-cloud-blueprint#2]
Build, sign and deploy the built Blueprint artifacts for all three OS (Windows, Linux, Mac) to the Eclipse download area. This is done via the [Eclipse hosted Jenkins instance](https://ci.eclipse.org/cdt-cloud/).

**Comment by sdirix** [comment]
Update: Created a ticket regarding the SSH errors: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1162

**Comment by sdirix** [comment]
Note the name change for CDT.cloud identifiers on Eclipse's infrastructure: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1195

**Comment by jfaltermeier** [comment]
PR for adding additional Jenkins Plugins: https://github.com/eclipse-cbi/jiro/pull/208

**Comment by jfaltermeier** [comment]
Issue regarding Mac and Windows Build nodes: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1288

**Comment by sdirix** [comment]
@jfaltermeier Is the Jenkins build now pointing to the `cdt-cloud-blueprint` master and run automatically on every push? If yes then please close the issue here.

**Comment by jfaltermeier** [comment]
Branch is updated now. Build will check every 15 minutes for new commits.
