### ISSUE TITLE
Add a launch config to run the CMake example

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-cdt-cloud/cdt-cloud-blueprint#44]
### Feature Description:

The CMake example contains a launch config to debug the example. It would be nice to also have one that just runs the example without debugging

**Comment by JonasHelming** [comment]
@planger When will this be available in the CDT Cloud BP Download?

**Comment by planger** [comment]
@JonasHelming  We plan a new release of CDT Cloud BP about one month after the Theia community release.
