### ISSUE TITLE
Performance of build is slow

### ISSUE THREAD

**Issue by MatthewKhouzam** [eclipse-cdt-cloud/cdt-cloud-blueprint#66]
The build of CDT Cloud Blueprints is not very good, making development difficult.

On my 11th Gen Intel Core i5-1145G7 with a PCI NVME and 32 GB Ram, the build takes between 6 and 13 minutes. This is when all the plug-ins are downloaded.
### Steps to Reproduce:

1. run `yarn`
2. Wait 5-10 minutes
3. run `yarn electron package`

### Additional Information

- Operating System: Linux Kernel 5.15
- Theia Version: 1.38

Here's a breakdown:

`yarn`

* Total time: 330 s
* cdt-cloud-blueprint:prepare : 180s
* cdt-cloud-blueprint-docker:prepare : 60 s
* cdt-cloud-blueprint-browser:prepare: 60s
* cdt-cloud-blueprint-product:prepare: fast
* @eclipse-cdt-cloud/blueprint-example-generator:prepare: fast
* cdt-cloud-blueprint-updater:prepare: fast
* cdt-cloud-blueprint-launcher:prepare: fast

`yarn electron package`

* Total time: 220 s
* Building AppImage:  30 s
* Building Deb: 160 s

Hope this helps

**Comment by sdirix** [comment]
I agree, we should not cram everything into the `yarn prepare` invocation. In `yarn` prepare we should only build the extensions so that linting, type hints etc. work in the editor of choice.
We should keep an "all" script for lazy users which does "everything" and split the rest up. This then also needs to be documented in the README.

**Comment by sdirix** [comment]
Hi @MatthewKhouzam,

The scripts were reworked a bit and we enhanced the documentation in regards to the build steps to perform. Can you check whether this problem is now solved from your point of view.

If there any problems, feel free to reopen the issue or create a new one. Thanks!
