### ISSUE TITLE
CDT Cloud Blueprint Update to Theia 1.45.1

### ISSUE THREAD

**Issue by sdirix** [eclipse-cdt-cloud/cdt-cloud-blueprint#83]
Update and release aligned with Theia 1.45.1

## Required Steps

- [x] Merge latest Theia Blueprint community release commit: `f037dcc411add2ee7460d9e32eef2d0b506d6476`
- [x] Update Theia to latest version of said community release: `1.45.1`
- [x] Update all consumed Theia extensions and VSCode extensions
- [x] Test packaged Electron Blueprint locally
- [x] Test Browser variant locally
- [x] Test DockerImage variant locally

After Merge

- [x] Verify that [Jenkins pipeline](https://ci.eclipse.org/theia/job/TheiaCDTCloud/job/master/) completed successfully
- [x] Download a previous release and check that update to latest version completes successfully

Deploy to try.theia-cloud.io:

- [x] Push built docker image to registry
- [x] Update [deployment file](https://github.com/eclipsesource/theia-cloud/blob/main/demo/k8s/appdefinitions/cdt.yaml) to use newly pushed docker image
- [x] Apply the [deployment file](https://github.com/eclipsesource/theia-cloud/blob/main/demo/k8s/appdefinitions/cdt.yaml) to the cluster
- [x] Verify that updated CDT Cloud Blueprint Online is available and works

Release announcement:

- [x] Announce release on the [cdt-cloud-dev](https://accounts.eclipse.org/mailing-list/cdt-cloud-dev) mailing list

**Comment by ndoschek** [comment]
Hi @sdirix,

I opened a PR here: https://github.com/eclipse-cdt-cloud/cdt-cloud-blueprint/pull/84

and completed the following steps:
- [x] Merge latest Theia Blueprint community release commit: f037dcc411add2ee7460d9e32eef2d0b506d6476
- [x] Update Theia to latest version of said community release: 1.45.1
- [x] Update all consumed Theia extensions and VSCode extensions
- [x] Test packaged Electron Blueprint locally
- [x] Test Browser variant locally
- [x] Test DockerImage variant locally

- [x] Ran E2E tests successfully (https://github.com/eclipse-cdt-cloud/cdt-cloud-blueprint?tab=readme-ov-file#running-e2e-tests)

Could you please mark the tasks as completed (and possibly add the E2E test step) and review the PR? TIA

**Comment by jfaltermeier** [comment]
The new link to the deployment file is https://github.com/eclipsesource/try-theia-cloud-deployment/blob/main/resources/appdefinitions/cdt.yaml

**Comment by sdirix** [comment]
All steps completed. Thanks @ndoschek and @jfaltermeier
