### ISSUE TITLE
CDT Cloud Blueprint update to Theia 1.49

### ISSUE THREAD

**Issue by sdirix** [eclipse-cdt-cloud/cdt-cloud-blueprint#89]
Update and release aligned with Theia 1.49.1

## Required Steps

- [x] Merge latest Theia Blueprint community release commit
- [x] if required: Update Theia to latest version of said community release
- [x] Update all consumed Theia extensions and VSCode extensions
- [x] Test packaged Electron Blueprint locally
- [x] Test Browser variant locally
- [x] Test Docker variant locally
- [x] Run E2E tests locally (https://github.com/eclipse-cdt-cloud/cdt-cloud-blueprint?tab=readme-ov-file#running-e2e-tests)

After Merge

- [x] Verify that [Jenkins pipeline](https://ci.eclipse.org/theia/job/TheiaCDTCloud/job/master/) completed successfully
- [x] [Download a previous release](https://download.eclipse.org/theia/cdt-cloud/) and check that update to latest version completes successfully

Deploy to try.theia-cloud.io:

- [x] Push docker image with version tag to registry via [GH action](https://github.com/eclipse-cdt-cloud/cdt-cloud-blueprint/actions/workflows/publish-image.yml)
- [x] Update [deployment file](https://github.com/eclipsesource/try-theia-cloud-deployment/blob/main/resources/appdefinitions/cdt.yaml) to use newly pushed docker image
- [x] Apply the [deployment file](https://github.com/eclipsesource/try-theia-cloud-deployment/blob/main/resources/appdefinitions/cdt.yaml) to the cluster
- [x] Verify that updated [CDT Cloud Blueprint Try Online](https://try.theia-cloud.io/?appDef=cdt-cloud-demo) is available and works

Release announcement:

- [x] Announce release on the [cdt-cloud-dev](https://accounts.eclipse.org/mailing-list/cdt-cloud-dev) mailing list

**Comment by sdirix** [comment]
@ndoschek will work on this

**Comment by ndoschek** [comment]
Hi @sdirix, I opened a PR of the update to Theia 1.49.1 here:
https://github.com/eclipse-cdt-cloud/cdt-cloud-blueprint/pull/90

I completed the first set of tasks from the description (but cannot mark them as done myself), could you check them for me? TIA

**Comment by sdirix** [comment]
@jfaltermeier will have a look at the current Jenkins failures
