### ISSUE TITLE
Update cdt-gdb-vscode

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cdt-cloud/cdt-cloud-blueprint#9]
At the moment this:
https://github.com/eclipse-cdt-cloud/cdt-cloud-blueprint/blob/6d0f6fbc1574d745062842ff736fcb64de842838/applications/electron/package.json#L135
is consuming cdt-gdb-vscode in a not very automated way in whole or in part because cdt-gdb-vscode is not published well.

Depends on: https://github.com/eclipse-cdt-cloud/cdt-gdb-vscode/issues/40

**Comment by planger** [comment]
Closed via https://github.com/eclipse-cdt-cloud/cdt-cloud-blueprint/pull/33
